---
- name: survey test
  hosts: FACN52
  gather_facts: false
  vars:
     lastname: "John"
     firstname: "doe"

 
  tasks:
   - name: First execution
     debug:
       msg: "{{ lastname }} }}"

   - name: First execution
     debug:
       msg: "{{ firstname }}"
   
  
  

  
