---
- name: survey test
  hosts: FACN52
  gather_facts: false
  vars:
     lastname: "John"
     firstname: "doe"
     age: 10

 
  tasks:
   - name: First execution
     debug:
       msg: "{{ lastname }} }}"
     tags: [ fam1]

   - name: Second execution
     debug:
       msg: "{{ firstname }}"
     tags: [ fam1, fam2 ]

   - name: Third exexution
     debug:
       msg: " {{ age  }}"
     tags: [ fam1, fam2, fam3]
   
  
  

  
